export const elements = {
  login: document.querySelector("#login"),
  app: document.querySelector("#app"),
  loginForm: document.querySelector(".login-card"),
  formMessage: document.querySelector(".form-message"),
  routeButtons: document.querySelectorAll("[data-route]"),
  views: document.querySelectorAll("[data-view]"),
  navButtons: document.querySelectorAll(".nav-links [data-route]"),
  roleBadge: document.querySelector("[data-role-badge]"),
  userName: document.querySelector("[data-user-name]"),
  cartCount: document.querySelector("[data-cart-count]"),
  cartSummary: document.querySelector("[data-cart-summary]"),
  homeProducts: document.querySelector("[data-home-products]"),
  catalogProducts: document.querySelector("[data-catalog-products]"),
  cartList: document.querySelector("[data-cart-list]"),
  checkoutSubmitButton: document.querySelector("[data-checkout-submit]"),
  historyList: document.querySelector("[data-history-list]"),
  listingGrid: document.querySelector("[data-listings]"),
  filterButtons: document.querySelectorAll("[data-filter]"),
  categoryButtons: document.querySelectorAll("[data-category]"),
  actionButtons: document.querySelectorAll("[data-action]"),
  addCartButton: document.querySelector("[data-add-cart]"),
  newsletters: document.querySelectorAll("form.newsletter"),
  settingsForm: document.querySelector("[data-settings-form]"),
  profileForm: document.querySelector("[data-profile-form]"),
  newListingForm: document.querySelector("[data-new-listing-form]"),
  databaseStats: document.querySelector("[data-database-stats]"),
  exportDatabaseButton: document.querySelector("[data-export-database]"),
  resetDatabaseButton: document.querySelector("[data-reset-database]"),
  toast: document.querySelector("[data-toast]")
};
